name: Draft Artifacts

on: [push]

jobs:
  build-macOS:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn global add node-gyp && yarn install --frozen-lockfile

      - name: Prepare for app notarization
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.APPLE_API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8

      - name: Build
        run: yarn build:mac
        env:
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_KEY_ISSUER_ID: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      # - name: Upload .zip
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: ark-desktop-wallet-mac-2.8.1.zip
      #     path: build/target/ark-desktop-wallet-mac-2.8.1.zip

      - name: Upload .dmg
        uses: actions/upload-artifact@v1
        with:
          name: ark-desktop-wallet-mac-2.8.1-${{ github.sha }}.dmg
          path: build/target/ark-desktop-wallet-mac-2.8.1.dmg

  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn global add node-gyp && yarn install --frozen-lockfile
        shell: cmd

      - name: Build
        run: yarn build:win
        shell: cmd
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Upload .exe
        uses: actions/upload-artifact@v1
        with:
          name: ark-desktop-wallet-win-2.8.1-${{ github.sha }}.exe
          path: build/target/ark-desktop-wallet-win-2.8.1.exe
