name: Draft Artifacts

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn global add node-gyp && yarn install --frozen-lockfile
        shell: cmd

      - name: Build
        run: yarn build:win
        shell: cmd
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Upload .exe
        uses: actions/upload-artifact@v1
        with:
          name: ark-desktop-wallet-win-2.8.1-${{ github.sha }}.exe
          path: build/target/ark-desktop-wallet-win-2.8.1.exe
